version: "3"

services:
  api:
    container_name: flashcards-api
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: development
      PORT: 3333
      DB_HOST: flashcards-postgres
    volumes:
      - .:/usr/app:delegated
      - node_modules:/usr/node_modules
    networks:
      - app-connect
    ports:
      - 3333:3333
      - 9229:9229

  postgres:
    container_name: flashcards-postgres
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./resources/postgresql:/var/lib/postgresql/data
    networks:
      - app-connect

  postgres-test:
    container_name: flashcards-postgres-test
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - ./resources/postgresql-test:/var/lib/postgresql-test/data
    ports:
      - 5433:5432
    networks:
      - app-connect

volumes:
  node_modules:
  postgres:
  postgres-test:


networks:
  app-connect:
    driver: bridge
