version: "3"

services:
  api:
    container_name: flashcards-api
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: unless-stopped
    env_file: .env
    environment:
      PORT: 3333
      DB_HOST: flashcards-postgres
    volumes:
      - .:/usr/app/
      - node_modules:/usr/app/node_modules
    networks:
      - app-connect
    ports:
      - 3333:3333
      - 9229:9229
    command: yarn dev

  postgres:
    container_name: flashcards-postgres
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./resources/postgresql:/var/lib/postgresql/data
    networks:
      - app-connect

volumes:
  postgres:
  node_modules:

networks:
  app-connect:
    driver: bridge
