version: "3"

services:
  postgres:
    container_name: flashcards-postgres
    image: postgres:13-alpine
    restart: "no"
    environment:
      POSTGRES_DB: flashcards
      POSTGRES_USER: marciorasf
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - flashcards-postgres:/var/lib/postgresql/data
      - ./scripts/db-initialization/:/docker-entrypoint-initdb.d/
    networks:
      - flashcards-net

volumes:
  flashcards-postgres:

networks:
  flashcards-net:
    driver: bridge
