version: "3"

services:
  postgres:
    container_name: flashcards-postgres
    image: postgres:13-alpine
    restart: "no"
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - flashcards-postgres:/var/lib/postgresql/data
    networks:
      - flashcards-net

volumes:
  flashcards-postgres:

networks:
  flashcards-net:
    driver: bridge
